### PR TITLE
Add RelativeSolutionTolerance option

### PR DESCRIPTION
**Pull request by akshaysridhar**
Add new specialisation  `RelativeSolutionTolerance{FT} <: AbstractTolerance{FT}` + test + API docs update.
	modified:   src/RootSolvers.jl
	modified:   test/test_helper.jl
        modified:   docs/src/API.md
Bump minor version -> 0.3.4

# PULL REQUEST

## Purpose and Content
Adds a convergence criteria based on relative difference between consecutive iterations. 

## Benefits and Risks
Provides an additional option for convergence criteria. 
Risks: Can be mitigated through appropriate tests. 

## PR Checklist
- [ ] This PR has a corresponding issue OR is linked to an SDI.
- [x] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [x] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [x] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [x] I linted my code on my local machine prior to submission OR N/A.
- [x] Unit tests are included OR N/A.
- [x] Code used in an integration test OR N/A.
- [x] All tests ran successfully on my local machine OR N/A.
- [x] All classes, modules, and function contain docstrings OR N/A.
- [x] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Comment by akshaysridhar** [comment]
@charleskawczynski Are there suggestions for additional tests here ?

**Review by charleskawczynski — APPROVED** [review]
LGTM. Feel free to bump the version for a release. The only thing that looks like it could technically be breaking is that `RelativeSolutionTolerance` is exported (and could conflict with other things in scope), but it's probably fine. I think we've been using `import` mostly anyway.

**Comment by akshaysridhar** [comment]
Rebasing before merge; Do you suggest splitting the version bump PR or just including it here ?

**Comment by charleskawczynski** [comment]
Including it here is fine

**Review by akshaysridhar — COMMENTED** [review]
@JuliaRegistrator register()

**Pull request merged**
